Repository nathan29849/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#3 [FE] Chore: 프로젝트 세팅
  FE/.eslintignore
  FE/.eslintrc.js
  FE/.gitignore
  FE/.keep
  FE/.prettierrc.js
  FE/config/webpack.common.js
  FE/config/webpack.dev.js
  FE/config/webpack.prod.js
  FE/env/.env
  FE/package.json
  FE/public/index.html
  FE/public/mockServiceWorker.js
  FE/src/App.tsx
  FE/src/assets/fonts/issue-tracker.svg
  FE/src/assets/fonts/issue-tracker.ttf
  FE/src/assets/fonts/issue-tracker.woff
  FE/src/assets/style.css
  FE/src/index.tsx
  FE/src/mocks/browsers/index.js
  FE/src/mocks/handlers/index.js
  FE/tsconfig.json
  FE/yarn.lock
Labels: FE

#10 [FE] Style: 아이콘 폰트 컴포넌트 #7
  FE/.eslintrc.js
  FE/.prettierrc.js
  FE/package.json
  FE/src/App.tsx
  FE/src/IconPage.tsx
  FE/src/assets/style.css
  FE/src/components/Icons/index.tsx
  FE/src/components/Icons/modules/CheckBox.tsx
  FE/src/components/Icons/modules/Circle.tsx
  FE/src/components/Icons/modules/Etc.tsx
  FE/src/components/Icons/modules/Logo.tsx
  FE/src/components/Icons/modules/style.ts
  FE/yarn.lock
Labels: FE, Feature

#11 [FE/공통작업] 공통으로 사용되어지는 스타일 GlobalStyle 작업
  FE/src/index.css
  FE/src/index.tsx
  FE/src/styles/GlobalStyle.tsx
  FE/src/styles/mixin.ts
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
Labels: FE, Feature

#12 [FE/공통작업] 라우터 분리 작업
  FE/src/App.tsx
  FE/src/Router.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/Layout.tsx
  FE/src/pages/Issue.tsx
  FE/src/pages/Label.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/Milestone.tsx
  FE/src/pages/NotFound.tsx
Labels: FE, Feature

#13 [FE/공통작업] recoil, reqct-query library settings
  FE/src/index.tsx
  FE/src/mocks/handlers/index.js
  FE/src/recoil/atoms/user.tsx
  FE/src/recoil/selectors/user.tsx
  FE/tsconfig.json
Labels: FE, Feature

#14 Backend/feature/#2 o auth
  BE/build.gradle
  BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthService.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/domain/JwtFactory.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/domain/github/GithubOAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/domain/github/GithubToken.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/domain/github/GithubUser.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/domain/github/OAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
  BE/src/main/java/codesquad/backend/issuetracker/user/domain/User.java
  BE/src/main/java/codesquad/backend/issuetracker/user/infrastructure/UserRepository.java
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/backend/issuetracker/oauth/AuthControllerTest.java
  BE/src/test/java/codesquad/backend/issuetracker/oauth/JwtTest.java
Labels: BE, Feature

#28 [FE] Issue Page Header
  FE/.eslintrc.js
  FE/src/Router.tsx
  FE/src/assets/ad.css
  FE/src/assets/fonts/ad.svg
  FE/src/assets/fonts/ad.ttf
  FE/src/assets/fonts/ad.woff
  FE/src/components/Button/index.tsx
  FE/src/components/Button/style.ts
  FE/src/components/FilterBar/index.tsx
  FE/src/components/FilterBar/style.ts
  FE/src/components/Header/index.tsx
  FE/src/components/Header/style.ts
  FE/src/components/Icons/modules/Etc.tsx
  FE/src/components/Icons/modules/Logo.tsx
  FE/src/components/Layout.tsx
  FE/src/components/TabList/Tab/index.jsx
  FE/src/components/TabList/Tab/style.ts
  FE/src/components/TabList/index.tsx
  FE/src/components/TabList/style.ts
  FE/src/index.tsx
  FE/src/pages/ButtonPage/index.tsx
  FE/src/pages/IconPage/index.tsx
  FE/src/pages/Issue.tsx
  FE/src/pages/IssuePage/index.tsx
  FE/src/pages/IssuePage/style.ts
  FE/src/pages/Label.tsx
  FE/src/pages/Label/index.tsx
  FE/src/pages/Login/index.tsx
  FE/src/pages/Milestone.tsx
  FE/src/pages/Milestone/index.tsx
  FE/src/pages/NotFound/index.tsx
  FE/src/styles/GlobalStyle.tsx
  FE/src/styles/mixin.ts
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
Labels: FE, Feature

#29 [FE] Login Page UI
  FE/src/App.tsx
  FE/src/components/Button/index.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/Header/style.ts
  FE/src/components/UserAvatar/index.tsx
  FE/src/components/UserAvatar/style.ts
  FE/src/pages/ButtonPage/index.tsx
  FE/src/pages/Login/index.tsx
  FE/src/pages/Login/style.ts
  FE/src/utils/types.ts
Labels: FE, Feature

#32 [FE] Rename IssuePage
  FE/src/pages/IssuePage.tsx
  FE/src/pages/IssuePage/index.tsx
  FE/src/pages/IssuePage/style.ts
Labels: FE

#36 Fe feat/#4 indicator
  FE/src/Indicator/ProgressBar/index.tsx
  FE/src/Indicator/ProgressBar/style.ts
  FE/src/components/Button/index.tsx
  FE/src/pages/Login/index.tsx
  FE/src/pages/Login/style.ts
  FE/tsconfig.json
Labels: FE

#46 [Muffin] 타입스크립트에서 any로 타입지정한 부분들 수정, 팝업 로직 분리
  FE/src/components/FilterBar/index.tsx
  FE/src/components/FilterBar/style.ts
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Issue/Item/index.tsx
  FE/src/components/Issue/Navigation/index.tsx
  FE/src/components/Popup/Contents.tsx
  FE/src/components/Popup/Item.tsx
  FE/src/components/Popup/type.ts
  FE/src/hooks/useComponentVisible.jsx
Labels: FE, Feature

#47 [FE][Cola] useSearch Hook 추가
  FE/src/components/Button/style.ts
  FE/src/hooks/useSearch.tsx
Labels: FE, Feature

#48 [FE][Cola] 팝업 UI 스타일 작업
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Popup/Contents.tsx
  FE/src/components/Popup/style.tsx
  FE/src/pages/IssuePage/style.ts
  FE/src/styles/theme.ts
Labels: FE, Feature

#56 [FE][Cola] Radio Option Selection 컴포넌트
  FE/src/components/Icons/modules/Circle.tsx
  FE/src/components/RadioSelection/index.tsx
  FE/src/components/RadioSelection/style.ts
  FE/src/styles/mixin.ts
Labels: FE, Feature

#59 [BE] interceptor를 이용한 login 구현
  BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
  BE/src/main/java/codesquad/backend/issuetracker/common/config/WebConfig.java
  BE/src/main/java/codesquad/backend/issuetracker/exception/AuthException.java
  BE/src/main/java/codesquad/backend/issuetracker/exception/AuthExceptionHandler.java
  BE/src/main/java/codesquad/backend/issuetracker/exception/ErrorCode.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/GithubOAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/JwtFactory.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthService.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/AuthInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/CommonInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/interceptor/RefreshInterceptor.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/dto/GithubLoginUserDto.java
  BE/src/main/java/codesquad/backend/issuetracker/user/domain/User.java
  BE/src/main/java/codesquad/backend/issuetracker/user/infrastructure/UserRepository.java
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/backend/issuetracker/oauth/JwtTest.java
Labels: enhancement, BE, Feature

#58 [FE][Muffin]: Popup 컴포넌트 데이터 넘기는 작업 진행, 팝업 내 항목 클릭 시 팝업 닫히지 않는 현상 해결
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Popup/Contents.tsx
  FE/src/components/Popup/index.tsx
  FE/src/components/Popup/style.tsx
  FE/src/components/Popup/type.ts
  FE/src/hooks/useComponentVisible.jsx
Labels: FE, Feature

#62 [FE][Cola] Text Input 컴포넌트 추가
  FE/src/components/Input/index.tsx
  FE/src/components/Input/style.ts
Labels: FE, Feature

#65 [FE][Muffin] 팝업 기능 타입 지정
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/components/Popup/Contents.tsx
  FE/src/recoil/atoms/issue.ts
Labels: FE, Feature

#66 [FE][Cola] useSearch 리팩토링 및 파라미터 사용방법 추가
  FE/src/hooks/useSearch.tsx
Labels: FE, Feature

#67 [FE][Muffin] 레이블 페이지 UI 작업
  FE/src/Router.tsx
  FE/src/components/Label/Form.tsx
  FE/src/components/Label/formStyle.ts
  FE/src/mocks/handlers/index.js
  FE/src/pages/Label/index.tsx
  FE/src/pages/LabelPage/index.tsx
  FE/src/pages/LabelPage/style.ts
Labels: FE, Feature

#71 [FE][Muffin] 이슈 필터 기능 URL params
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/mocks/handlers/index.js
Labels: FE, Feature

#74 [FE][Muffin] 팝업 Url Param 추가 기능구현
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Issue/Item/index.tsx
  FE/src/components/Issue/Item/style.ts
  FE/src/components/Issue/Navigation/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/components/Issue/style.ts
  FE/src/components/Popup/Item.tsx
  FE/src/components/Popup/style.tsx
  FE/src/mocks/handlers/index.js
  FE/src/recoil/atoms/label.ts
  FE/src/recoil/atoms/milestone.ts
Labels: FE, Feature

#77 [FE][Cola] Textarea 컴포넌트 UI 구현
  FE/.eslintrc.js
  FE/src/components/Input/index.tsx
  FE/src/components/Input/style.ts
Labels: FE, Feature

#78 [FE][Muffin] 레이블 페이지 레이아웃 작업
  FE/src/components/Label/Form.tsx
  FE/src/components/Label/formStyle.ts
  FE/src/components/Popup/style.tsx
  FE/src/pages/LabelPage/index.tsx
  FE/src/recoil/atoms/label.ts
  FE/src/utils/animation.ts
Labels: FE, Feature

#79 [FE][Cola] New Issue 페이지 UI
  FE/config/webpack.common.js
  FE/src/Router.tsx
  FE/src/components/Input/index.tsx
  FE/src/components/Input/style.ts
  FE/src/components/Layout/index.tsx
  FE/src/components/UserAvatar/style.ts
  FE/src/pages/IssuePage/Detail/Header/index.tsx
  FE/src/pages/IssuePage/Detail/Header/style.ts
  FE/src/pages/IssuePage/Detail/Main/index.tsx
  FE/src/pages/IssuePage/Detail/Main/style.ts
  FE/src/pages/IssuePage/Detail/index.tsx
  FE/src/pages/IssuePage/Detail/style.ts
  FE/src/pages/IssuePage/index.tsx
  FE/yarn.lock
Labels: FE, Feature

#81 [FE][Cola] Fix useSearch hook
  FE/src/hooks/useSearch.tsx
Labels: FE, fix

#84 add: @ConfigurationProperties 를 적용하여 @Value 제거 및 불필요한 의존성 제거
  BE/build.gradle
  BE/src/main/java/codesquad/backend/issuetracker/BeApplication.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/GithubOAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/JwtFactory.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/application/OAuthClient.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/config/OAuthProperties.java
  BE/src/main/java/codesquad/backend/issuetracker/oauth/presentation/controller/GithubAuthController.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/auth/auth.yml
  BE/src/test/java/codesquad/backend/issuetracker/oauth/AuthControllerTest.java
Labels: enhancement, BE

#85 [FE-Fix][Muffin] 네비게이션 안에있는 열린이슈, 닫힌 이슈 색상 변경 오류
  FE/src/components/Issue/Navigation/index.tsx
Labels: bug, FE

#88 [FE][Cola] Login
  FE/.eslintrc.js
  FE/src/Router.tsx
  FE/src/apis/login.ts
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Header/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/constants/cookie.ts
  FE/src/constants/default.ts
  FE/src/hooks/useComponentVisible.tsx
  FE/src/hooks/useIsLoggedIn.tsx
  FE/src/hooks/useLogin.tsx
  FE/src/hooks/useLogout.tsx
  FE/src/mocks/handlers/GitHubLogin.js
  FE/src/mocks/handlers/index.js
  FE/src/pages/AccessDeniedPage/index.tsx
  FE/src/pages/Callback/index.tsx
  FE/src/pages/Login/index.tsx
  FE/src/pages/Verification/index.tsx
  FE/src/recoil/atoms/user.tsx
  FE/src/type/user.ts
  FE/src/utils/cookie.ts
  FE/tsconfig.json
Labels: FE, Feature

#93 [FE][Muffin] useDebounce 훅을 만들어서 검색 인풋창 글자수 체킹 적용하기
  FE/src/components/FilterBar/index.tsx
  FE/src/components/FilterBar/style.ts
  FE/src/constants/default.ts
  FE/src/hooks/useDebouce.tsx
Labels: FE, Feature

#95 feat: [90] milestone 삭제 및 milestoneIdDto 생성
  BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/controller/MilestoneController.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneIdDto.java
Labels: BE, Feature

#96 [FE][Cola] 이슈 작성 페이지, 이슈 디테일 페이지 (Header)
  FE/src/Router.tsx
  FE/src/apis/issue.ts
  FE/src/components/Button/index.tsx
  FE/src/components/Button/style.ts
  FE/src/components/Indicator/Loader/index.tsx
  FE/src/components/Input/index.tsx
  FE/src/components/UserAvatar/index.tsx
  FE/src/hooks/useInput.tsx
  FE/src/hooks/usePostIssue.tsx
  FE/src/mocks/handlers/PostIssue.js
  FE/src/mocks/handlers/index.js
  FE/src/pages/Callback/index.tsx
  FE/src/pages/IssuePage/Detail/Main/index.tsx
  FE/src/pages/IssuePage/Detail/Main/style.ts
  FE/src/pages/Verification/index.tsx
Labels: FE, Feature

#98 [FE][Muffin] 레이블 페이지 기능 작업 진행
  FE/.eslintrc.js
  FE/public/index.html
  FE/src/components/Label/Form.tsx
  FE/src/components/Label/formStyle.ts
  FE/src/components/Modal/index.tsx
  FE/src/components/Modal/style.ts
  FE/src/constants/default.ts
  FE/src/mocks/handlers/index.js
  FE/src/pages/LabelPage/index.tsx
  FE/src/pages/LabelPage/style.ts
  FE/src/recoil/atoms/label.ts
  FE/src/recoil/atoms/milestone.ts
Labels: FE, Feature

#99 [FE][Muffin] PR review refactor
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/Navigation/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/components/Popup/Item.tsx
  FE/src/components/Popup/type.ts
  FE/src/hooks/useComponentVisible.tsx
Labels: bug, FE

#100 Backend/feature/#90 milestone crud
  BE/src/main/java/codesquad/backend/issuetracker/issue/domain/Issue.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/infrastructure/MilestoneRepository.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/dto/MilestoneDto.java
  BE/src/main/resources/data.sql
Labels: BE, Feature

#103 [FE][Cola] SideBar Panel
  FE/src/apis/label.ts
  FE/src/apis/milestone.ts
  FE/src/apis/user.ts
  FE/src/components/SideBar/AssigneePanel.tsx
  FE/src/components/SideBar/Common.tsx
  FE/src/components/SideBar/LabelPanel.tsx
  FE/src/components/SideBar/MileStonePanel.tsx
  FE/src/components/SideBar/context/AssigneePanel/index.tsx
  FE/src/components/SideBar/context/LabelPanel/index.tsx
  FE/src/components/SideBar/context/MileStonePanel/index.tsx
  FE/src/components/SideBar/context/index.tsx
  FE/src/components/SideBar/index.tsx
  FE/src/components/SideBar/popupStyle.ts
  FE/src/components/SideBar/style.ts
  FE/src/components/UserAvatar/index.tsx
  FE/src/components/UserAvatar/style.ts
  FE/src/mocks/handlers/GetLabels.js
  FE/src/mocks/handlers/GetMileStones.js
  FE/src/mocks/handlers/GetUsers.js
  FE/src/mocks/handlers/index.js
  FE/src/styles/theme.ts
  FE/src/type/label.ts
  FE/src/type/milestone.ts
Labels: FE, Feature

#105 [FE][Muffin] url 값에 따라서 Search Input Value 셋팅
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Issue/Navigation/index.tsx
  FE/src/components/Popup/Contents.tsx
  FE/src/components/Popup/Item.tsx
  FE/src/constants/default.ts
Labels: FE, Feature

#107 [FE][Cola] Compose 유틸리티 컴포넌트 구현
  FE/src/components/SideBar/context/index.tsx
  FE/src/components/SideBar/popupStyle.ts
  FE/src/utils/Compose.tsx
Labels: FE, Feature

#109 [FE][Muffin] 이슈 메인 페이지 체크박스 기능 구현
  FE/src/components/Issue/Item/index.tsx
  FE/src/components/Issue/Navigation/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/components/Label/Form.tsx
  FE/src/components/Popup/Item.tsx
  FE/src/pages/LabelPage/index.tsx
  FE/src/styles/GlobalStyle.tsx
Labels: FE

#110 [FE][Cola] Side Panel Utility
  FE/src/components/SideBar/AssigneePanel.tsx
  FE/src/components/SideBar/LabelPanel.tsx
  FE/src/components/SideBar/MileStonePanel.tsx
  FE/src/components/SideBar/context/AssigneePanel/index.tsx
  FE/src/components/SideBar/context/LabelPanel/index.tsx
  FE/src/components/SideBar/context/MileStonePanel/index.tsx
  FE/src/components/SideBar/context/index.tsx
  FE/src/components/SideBar/index.tsx
Labels: FE, Feature

#112 Backend/feature/#91 label crud
  BE/src/main/java/codesquad/backend/issuetracker/label/application/LabelService.java
  BE/src/main/java/codesquad/backend/issuetracker/label/domain/Label.java
  BE/src/main/java/codesquad/backend/issuetracker/label/infrastructure/LabelRepository.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/controller/LabelController.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelCountDto.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelDto.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/LabelsResponseDto.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/request/LabelCreateRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/request/LabelEditRequest.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/response/LabelCountResponse.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/response/LabelIdResponse.java
  BE/src/main/java/codesquad/backend/issuetracker/label/presentation/dto/response/LabelsResponse.java
  BE/src/main/java/codesquad/backend/issuetracker/milestone/presentation/controller/MilestoneController.java
Labels: BE, Feature

#118 [FE] fix: 3주차 PR 리뷰 반영 주로 네이밍 수정, 불필요한 로직 삭제
  FE/src/apis/issue.ts
  FE/src/apis/label.ts
  FE/src/apis/login.ts
  FE/src/apis/milestone.ts
  FE/src/apis/user.ts
  FE/src/components/FilterBar/index.tsx
  FE/src/components/Issue/Filter/index.tsx
  FE/src/components/Issue/Navigation/index.tsx
  FE/src/components/Issue/index.tsx
  FE/src/components/Label/Form.tsx
  FE/src/hooks/useSearch.tsx
Labels: fix

#119 [FE][Muffin]: 마일스톤 UI 작업 진행 완료
  FE/src/components/Indicator/Form.tsx
  FE/src/pages/Milestone/index.tsx
  FE/src/pages/Milestone/style.ts
Labels: FE, Feature

#126 [FE][Cola] 마일스톤 Panel 로직 수정
  FE/src/components/SideBar/MileStonePanel.tsx
  FE/src/components/SideBar/index.tsx
Labels: FE, Feature

#127 [FE][Muffin] 마일스톤 페이지 msw 더미데이터 READ, DELETE 기능 구현
  FE/src/apis/milestone.ts
  FE/src/components/Modal/style.ts
  FE/src/mocks/handlers/DeleteMileStone.js
  FE/src/mocks/handlers/GetMileStones.js
  FE/src/mocks/handlers/index.js
  FE/src/pages/LabelPage/index.tsx
  FE/src/pages/Milestone/index.tsx
  FE/src/pages/Milestone/style.ts
  FE/src/type/milestone.ts
Labels: FE
